##################### Trigger Channels ##########################

dbLoadRecords("${TOP}/BPMApp/Db/BPMTrigger.template", "P=${EPICS_HOSTNAME}, PORT=$(BPM_NAME), TRIGGER_CHAN=0,  ADDR=0,  BPM_NUMBER=$(BPM_NUMBER), TIMEOUT=1")
dbLoadRecords("${TOP}/BPMApp/Db/BPMTrigger.template", "P=${EPICS_HOSTNAME}, PORT=$(BPM_NAME), TRIGGER_CHAN=1,  ADDR=1,  BPM_NUMBER=$(BPM_NUMBER), TIMEOUT=1")
dbLoadRecords("${TOP}/BPMApp/Db/BPMTrigger.template", "P=${EPICS_HOSTNAME}, PORT=$(BPM_NAME), TRIGGER_CHAN=2,  ADDR=2,  BPM_NUMBER=$(BPM_NUMBER), TIMEOUT=1")
dbLoadRecords("${TOP}/BPMApp/Db/BPMTrigger.template", "P=${EPICS_HOSTNAME}, PORT=$(BPM_NAME), TRIGGER_CHAN=3,  ADDR=3,  BPM_NUMBER=$(BPM_NUMBER), TIMEOUT=1")
dbLoadRecords("${TOP}/BPMApp/Db/BPMTrigger.template", "P=${EPICS_HOSTNAME}, PORT=$(BPM_NAME), TRIGGER_CHAN=4,  ADDR=4,  BPM_NUMBER=$(BPM_NUMBER), TIMEOUT=1")
dbLoadRecords("${TOP}/BPMApp/Db/BPMTrigger.template", "P=${EPICS_HOSTNAME}, PORT=$(BPM_NAME), TRIGGER_CHAN=5,  ADDR=5,  BPM_NUMBER=$(BPM_NUMBER), TIMEOUT=1")
dbLoadRecords("${TOP}/BPMApp/Db/BPMTrigger.template", "P=${EPICS_HOSTNAME}, PORT=$(BPM_NAME), TRIGGER_CHAN=6,  ADDR=6,  BPM_NUMBER=$(BPM_NUMBER), TIMEOUT=1")
dbLoadRecords("${TOP}/BPMApp/Db/BPMTrigger.template", "P=${EPICS_HOSTNAME}, PORT=$(BPM_NAME), TRIGGER_CHAN=7,  ADDR=7,  BPM_NUMBER=$(BPM_NUMBER), TIMEOUT=1")
dbLoadRecords("${TOP}/BPMApp/Db/BPMTrigger.template", "P=${EPICS_HOSTNAME}, PORT=$(BPM_NAME), TRIGGER_CHAN=8,  ADDR=8,  BPM_NUMBER=$(BPM_NUMBER), TIMEOUT=1")
dbLoadRecords("${TOP}/BPMApp/Db/BPMTrigger.template", "P=${EPICS_HOSTNAME}, PORT=$(BPM_NAME), TRIGGER_CHAN=9,  ADDR=9,  BPM_NUMBER=$(BPM_NUMBER), TIMEOUT=1")
dbLoadRecords("${TOP}/BPMApp/Db/BPMTrigger.template", "P=${EPICS_HOSTNAME}, PORT=$(BPM_NAME), TRIGGER_CHAN=10, ADDR=10, BPM_NUMBER=$(BPM_NUMBER), TIMEOUT=1")
dbLoadRecords("${TOP}/BPMApp/Db/BPMTrigger.template", "P=${EPICS_HOSTNAME}, PORT=$(BPM_NAME), TRIGGER_CHAN=11, ADDR=11, BPM_NUMBER=$(BPM_NUMBER), TIMEOUT=1")
dbLoadRecords("${TOP}/BPMApp/Db/BPMTrigger.template", "P=${EPICS_HOSTNAME}, PORT=$(BPM_NAME), TRIGGER_CHAN=12, ADDR=12, BPM_NUMBER=$(BPM_NUMBER), TIMEOUT=1")
dbLoadRecords("${TOP}/BPMApp/Db/BPMTrigger.template", "P=${EPICS_HOSTNAME}, PORT=$(BPM_NAME), TRIGGER_CHAN=13, ADDR=13, BPM_NUMBER=$(BPM_NUMBER), TIMEOUT=1")
dbLoadRecords("${TOP}/BPMApp/Db/BPMTrigger.template", "P=${EPICS_HOSTNAME}, PORT=$(BPM_NAME), TRIGGER_CHAN=14, ADDR=14, BPM_NUMBER=$(BPM_NUMBER), TIMEOUT=1")
dbLoadRecords("${TOP}/BPMApp/Db/BPMTrigger.template", "P=${EPICS_HOSTNAME}, PORT=$(BPM_NAME), TRIGGER_CHAN=15, ADDR=15, BPM_NUMBER=$(BPM_NUMBER), TIMEOUT=1")
dbLoadRecords("${TOP}/BPMApp/Db/BPMTrigger.template", "P=${EPICS_HOSTNAME}, PORT=$(BPM_NAME), TRIGGER_CHAN=16, ADDR=16, BPM_NUMBER=$(BPM_NUMBER), TIMEOUT=1")
dbLoadRecords("${TOP}/BPMApp/Db/BPMTrigger.template", "P=${EPICS_HOSTNAME}, PORT=$(BPM_NAME), TRIGGER_CHAN=17, ADDR=17, BPM_NUMBER=$(BPM_NUMBER), TIMEOUT=1")
dbLoadRecords("${TOP}/BPMApp/Db/BPMTrigger.template", "P=${EPICS_HOSTNAME}, PORT=$(BPM_NAME), TRIGGER_CHAN=18, ADDR=18, BPM_NUMBER=$(BPM_NUMBER), TIMEOUT=1")
dbLoadRecords("${TOP}/BPMApp/Db/BPMTrigger.template", "P=${EPICS_HOSTNAME}, PORT=$(BPM_NAME), TRIGGER_CHAN=19, ADDR=19, BPM_NUMBER=$(BPM_NUMBER), TIMEOUT=1")
dbLoadRecords("${TOP}/BPMApp/Db/BPMTrigger.template", "P=${EPICS_HOSTNAME}, PORT=$(BPM_NAME), TRIGGER_CHAN=20, ADDR=20, BPM_NUMBER=$(BPM_NUMBER), TIMEOUT=1")
dbLoadRecords("${TOP}/BPMApp/Db/BPMTrigger.template", "P=${EPICS_HOSTNAME}, PORT=$(BPM_NAME), TRIGGER_CHAN=21, ADDR=21, BPM_NUMBER=$(BPM_NUMBER), TIMEOUT=1")
dbLoadRecords("${TOP}/BPMApp/Db/BPMTrigger.template", "P=${EPICS_HOSTNAME}, PORT=$(BPM_NAME), TRIGGER_CHAN=22, ADDR=22, BPM_NUMBER=$(BPM_NUMBER), TIMEOUT=1")
dbLoadRecords("${TOP}/BPMApp/Db/BPMTrigger.template", "P=${EPICS_HOSTNAME}, PORT=$(BPM_NAME), TRIGGER_CHAN=23, ADDR=23, BPM_NUMBER=$(BPM_NUMBER), TIMEOUT=1")













































