##################### ADC Waveforms ##########################

NDStdArraysConfigure("ADC_A_Array", $(QSIZE), 0, "$(PORT)", 0)
dbLoadRecords("$(AREA_DETECTOR)/ADApp/Db/NDPluginBase.template","P=${EPICS_HOSTNAME}-$(BPM_NUMBER):,R=ADC_A:,PORT=ADC_A_Array,ADDR=0,TIMEOUT=1,NDARRAY_PORT=$(PORT),NDARRAY_ADDR=0")
dbLoadRecords("$(AREA_DETECTOR)/ADApp/Db/NDStdArrays.template", "P=${EPICS_HOSTNAME}-$(BPM_NUMBER):,R=ADC_A:,PORT=ADC_A_Array,ADDR=0,TIMEOUT=1,TYPE=Int16,FTVL=SHORT,NELEMENTS=$(WAVEFORM_MAX_POINTS)")

NDStdArraysConfigure("ADC_B_Array", $(QSIZE), 0, "$(PORT)", 1)
dbLoadRecords("$(AREA_DETECTOR)/ADApp/Db/NDPluginBase.template","P=${EPICS_HOSTNAME}-$(BPM_NUMBER):,R=ADC_B:,PORT=ADC_B_Array,ADDR=0,TIMEOUT=1,NDARRAY_PORT=$(PORT),NDARRAY_ADDR=1")
dbLoadRecords("$(AREA_DETECTOR)/ADApp/Db/NDStdArrays.template", "P=${EPICS_HOSTNAME}-$(BPM_NUMBER):,R=ADC_B:,PORT=ADC_B_Array,ADDR=0,TIMEOUT=1,TYPE=Int16,FTVL=SHORT,NELEMENTS=$(WAVEFORM_MAX_POINTS)")

NDStdArraysConfigure("ADC_C_Array", $(QSIZE), 0, "$(PORT)", 2)
dbLoadRecords("$(AREA_DETECTOR)/ADApp/Db/NDPluginBase.template","P=${EPICS_HOSTNAME}-$(BPM_NUMBER):,R=ADC_C:,PORT=ADC_C_Array,ADDR=0,TIMEOUT=1,NDARRAY_PORT=$(PORT),NDARRAY_ADDR=2")
dbLoadRecords("$(AREA_DETECTOR)/ADApp/Db/NDStdArrays.template", "P=${EPICS_HOSTNAME}-$(BPM_NUMBER):,R=ADC_C:,PORT=ADC_C_Array,ADDR=0,TIMEOUT=1,TYPE=Int16,FTVL=SHORT,NELEMENTS=$(WAVEFORM_MAX_POINTS)")

NDStdArraysConfigure("ADC_D_Array", $(QSIZE), 0, "$(PORT)", 3)
dbLoadRecords("$(AREA_DETECTOR)/ADApp/Db/NDPluginBase.template","P=${EPICS_HOSTNAME}-$(BPM_NUMBER):,R=ADC_D:,PORT=ADC_D_Array,ADDR=0,TIMEOUT=1,NDARRAY_PORT=$(PORT),NDARRAY_ADDR=3")
dbLoadRecords("$(AREA_DETECTOR)/ADApp/Db/NDStdArrays.template", "P=${EPICS_HOSTNAME}-$(BPM_NUMBER):,R=ADC_D:,PORT=ADC_D_Array,ADDR=0,TIMEOUT=1,TYPE=Int16,FTVL=SHORT,NELEMENTS=$(WAVEFORM_MAX_POINTS)")

##################### ADC SWAP Waveforms ##########################

NDStdArraysConfigure("ADCSWAP_A_Array", $(QSIZE), 0, "$(PORT)", 5)
dbLoadRecords("$(AREA_DETECTOR)/ADApp/Db/NDPluginBase.template","P=${EPICS_HOSTNAME}-$(BPM_NUMBER):,R=ADCSWAP_A:,PORT=ADCSWAP_A_Array,ADDR=0,TIMEOUT=1,NDARRAY_PORT=$(PORT),NDARRAY_ADDR=5")
dbLoadRecords("$(AREA_DETECTOR)/ADApp/Db/NDStdArrays.template", "P=${EPICS_HOSTNAME}-$(BPM_NUMBER):,R=ADCSWAP_A:,PORT=ADCSWAP_A_Array,ADDR=0,TIMEOUT=1,TYPE=Int16,FTVL=SHORT,NELEMENTS=$(WAVEFORM_MAX_POINTS)")

NDStdArraysConfigure("ADCSWAP_B_Array", $(QSIZE), 0, "$(PORT)", 6)
dbLoadRecords("$(AREA_DETECTOR)/ADApp/Db/NDPluginBase.template","P=${EPICS_HOSTNAME}-$(BPM_NUMBER):,R=ADCSWAP_B:,PORT=ADCSWAP_B_Array,ADDR=0,TIMEOUT=1,NDARRAY_PORT=$(PORT),NDARRAY_ADDR=6")
dbLoadRecords("$(AREA_DETECTOR)/ADApp/Db/NDStdArrays.template", "P=${EPICS_HOSTNAME}-$(BPM_NUMBER):,R=ADCSWAP_B:,PORT=ADCSWAP_B_Array,ADDR=0,TIMEOUT=1,TYPE=Int16,FTVL=SHORT,NELEMENTS=$(WAVEFORM_MAX_POINTS)")

NDStdArraysConfigure("ADCSWAP_C_Array", $(QSIZE), 0, "$(PORT)", 7)
dbLoadRecords("$(AREA_DETECTOR)/ADApp/Db/NDPluginBase.template","P=${EPICS_HOSTNAME}-$(BPM_NUMBER):,R=ADCSWAP_C:,PORT=ADCSWAP_C_Array,ADDR=0,TIMEOUT=1,NDARRAY_PORT=$(PORT),NDARRAY_ADDR=7")
dbLoadRecords("$(AREA_DETECTOR)/ADApp/Db/NDStdArrays.template", "P=${EPICS_HOSTNAME}-$(BPM_NUMBER):,R=ADCSWAP_C:,PORT=ADCSWAP_C_Array,ADDR=0,TIMEOUT=1,TYPE=Int16,FTVL=SHORT,NELEMENTS=$(WAVEFORM_MAX_POINTS)")

NDStdArraysConfigure("ADCSWAP_D_Array", $(QSIZE), 0, "$(PORT)", 8)
dbLoadRecords("$(AREA_DETECTOR)/ADApp/Db/NDPluginBase.template","P=${EPICS_HOSTNAME}-$(BPM_NUMBER):,R=ADCSWAP_D:,PORT=ADCSWAP_D_Array,ADDR=0,TIMEOUT=1,NDARRAY_PORT=$(PORT),NDARRAY_ADDR=8")
dbLoadRecords("$(AREA_DETECTOR)/ADApp/Db/NDStdArrays.template", "P=${EPICS_HOSTNAME}-$(BPM_NUMBER):,R=ADCSWAP_D:,PORT=ADCSWAP_D_Array,ADDR=0,TIMEOUT=1,TYPE=Int16,FTVL=SHORT,NELEMENTS=$(WAVEFORM_MAX_POINTS)")

##################### TBT AMP Waveforms ##########################

NDStdArraysConfigure("TBT_A_Array", $(QSIZE), 0, "$(PORT)", 10)
dbLoadRecords("$(AREA_DETECTOR)/ADApp/Db/NDPluginBase.template","P=${EPICS_HOSTNAME}-$(BPM_NUMBER):,R=TBT_A:,PORT=TBT_A_Array,ADDR=0,TIMEOUT=1,NDARRAY_PORT=$(PORT),NDARRAY_ADDR=10")
dbLoadRecords("$(AREA_DETECTOR)/ADApp/Db/NDStdArrays.template", "P=${EPICS_HOSTNAME}-$(BPM_NUMBER):,R=TBT_A:,PORT=TBT_A_Array,ADDR=0,TIMEOUT=1,TYPE=Int32,FTVL=LONG,NELEMENTS=$(WAVEFORM_MAX_POINTS)")

NDStdArraysConfigure("TBT_B_Array", $(QSIZE), 0, "$(PORT)", 11)
dbLoadRecords("$(AREA_DETECTOR)/ADApp/Db/NDPluginBase.template","P=${EPICS_HOSTNAME}-$(BPM_NUMBER):,R=TBT_B:,PORT=TBT_B_Array,ADDR=0,TIMEOUT=1,NDARRAY_PORT=$(PORT),NDARRAY_ADDR=11")
dbLoadRecords("$(AREA_DETECTOR)/ADApp/Db/NDStdArrays.template", "P=${EPICS_HOSTNAME}-$(BPM_NUMBER):,R=TBT_B:,PORT=TBT_B_Array,ADDR=0,TIMEOUT=1,TYPE=Int32,FTVL=LONG,NELEMENTS=$(WAVEFORM_MAX_POINTS)")

NDStdArraysConfigure("TBT_C_Array", $(QSIZE), 0, "$(PORT)", 12)
dbLoadRecords("$(AREA_DETECTOR)/ADApp/Db/NDPluginBase.template","P=${EPICS_HOSTNAME}-$(BPM_NUMBER):,R=TBT_C:,PORT=TBT_C_Array,ADDR=0,TIMEOUT=1,NDARRAY_PORT=$(PORT),NDARRAY_ADDR=12")
dbLoadRecords("$(AREA_DETECTOR)/ADApp/Db/NDStdArrays.template", "P=${EPICS_HOSTNAME}-$(BPM_NUMBER):,R=TBT_C:,PORT=TBT_C_Array,ADDR=0,TIMEOUT=1,TYPE=Int32,FTVL=LONG,NELEMENTS=$(WAVEFORM_MAX_POINTS)")

NDStdArraysConfigure("TBT_D_Array", $(QSIZE), 0, "$(PORT)", 13)
dbLoadRecords("$(AREA_DETECTOR)/ADApp/Db/NDPluginBase.template","P=${EPICS_HOSTNAME}-$(BPM_NUMBER):,R=TBT_D:,PORT=TBT_D_Array,ADDR=0,TIMEOUT=1,NDARRAY_PORT=$(PORT),NDARRAY_ADDR=13")
dbLoadRecords("$(AREA_DETECTOR)/ADApp/Db/NDStdArrays.template", "P=${EPICS_HOSTNAME}-$(BPM_NUMBER):,R=TBT_D:,PORT=TBT_D_Array,ADDR=0,TIMEOUT=1,TYPE=Int32,FTVL=LONG,NELEMENTS=$(WAVEFORM_MAX_POINTS)")

##################### TBT POS Waveforms ##########################

NDStdArraysConfigure("TBT_X_Array", $(QSIZE), 0, "$(PORT)", 15)
dbLoadRecords("$(AREA_DETECTOR)/ADApp/Db/NDPluginBase.template","P=${EPICS_HOSTNAME}-$(BPM_NUMBER):,R=TBT_X:,PORT=TBT_X_Array,ADDR=0,TIMEOUT=1,NDARRAY_PORT=$(PORT),NDARRAY_ADDR=15")
dbLoadRecords("$(AREA_DETECTOR)/ADApp/Db/NDStdArrays.template", "P=${EPICS_HOSTNAME}-$(BPM_NUMBER):,R=TBT_X:,PORT=TBT_X_Array,ADDR=0,TIMEOUT=1,TYPE=Int32,FTVL=LONG,NELEMENTS=$(WAVEFORM_MAX_POINTS)")

NDStdArraysConfigure("TBT_Y_Array", $(QSIZE), 0, "$(PORT)", 16)
dbLoadRecords("$(AREA_DETECTOR)/ADApp/Db/NDPluginBase.template","P=${EPICS_HOSTNAME}-$(BPM_NUMBER):,R=TBT_Y:,PORT=TBT_Y_Array,ADDR=0,TIMEOUT=1,NDARRAY_PORT=$(PORT),NDARRAY_ADDR=16")
dbLoadRecords("$(AREA_DETECTOR)/ADApp/Db/NDStdArrays.template", "P=${EPICS_HOSTNAME}-$(BPM_NUMBER):,R=TBT_Y:,PORT=TBT_Y_Array,ADDR=0,TIMEOUT=1,TYPE=Int32,FTVL=LONG,NELEMENTS=$(WAVEFORM_MAX_POINTS)")

NDStdArraysConfigure("TBT_Q_Array", $(QSIZE), 0, "$(PORT)", 17)
dbLoadRecords("$(AREA_DETECTOR)/ADApp/Db/NDPluginBase.template","P=${EPICS_HOSTNAME}-$(BPM_NUMBER):,R=TBT_Q:,PORT=TBT_Q_Array,ADDR=0,TIMEOUT=1,NDARRAY_PORT=$(PORT),NDARRAY_ADDR=17")
dbLoadRecords("$(AREA_DETECTOR)/ADApp/Db/NDStdArrays.template", "P=${EPICS_HOSTNAME}-$(BPM_NUMBER):,R=TBT_Q:,PORT=TBT_Q_Array,ADDR=0,TIMEOUT=1,TYPE=Int32,FTVL=LONG,NELEMENTS=$(WAVEFORM_MAX_POINTS)")

NDStdArraysConfigure("TBT_SUM_Array", $(QSIZE), 0, "$(PORT)", 18)
dbLoadRecords("$(AREA_DETECTOR)/ADApp/Db/NDPluginBase.template","P=${EPICS_HOSTNAME}-$(BPM_NUMBER):,R=TBT_SUM:,PORT=TBT_SUM_Array,ADDR=0,TIMEOUT=1,NDARRAY_PORT=$(PORT),NDARRAY_ADDR=18")
dbLoadRecords("$(AREA_DETECTOR)/ADApp/Db/NDStdArrays.template", "P=${EPICS_HOSTNAME}-$(BPM_NUMBER):,R=TBT_SUM:,PORT=TBT_SUM_Array,ADDR=0,TIMEOUT=1,TYPE=Int32,FTVL=LONG,NELEMENTS=$(WAVEFORM_MAX_POINTS)")

##################### FOFB AMP Waveforms ##########################

NDStdArraysConfigure("FOFB_A_Array", $(QSIZE), 0, "$(PORT)", 25)
dbLoadRecords("$(AREA_DETECTOR)/ADApp/Db/NDPluginBase.template","P=${EPICS_HOSTNAME}-$(BPM_NUMBER):,R=FOFB_A:,PORT=FOFB_A_Array,ADDR=0,TIMEOUT=1,NDARRAY_PORT=$(PORT),NDARRAY_ADDR=25")
dbLoadRecords("$(AREA_DETECTOR)/ADApp/Db/NDStdArrays.template", "P=${EPICS_HOSTNAME}-$(BPM_NUMBER):,R=FOFB_A:,PORT=FOFB_A_Array,ADDR=0,TIMEOUT=1,TYPE=Int32,FTVL=LONG,NELEMENTS=$(WAVEFORM_MAX_POINTS)")

NDStdArraysConfigure("FOFB_B_Array", $(QSIZE), 0, "$(PORT)", 26)
dbLoadRecords("$(AREA_DETECTOR)/ADApp/Db/NDPluginBase.template","P=${EPICS_HOSTNAME}-$(BPM_NUMBER):,R=FOFB_B:,PORT=FOFB_B_Array,ADDR=0,TIMEOUT=1,NDARRAY_PORT=$(PORT),NDARRAY_ADDR=26")
dbLoadRecords("$(AREA_DETECTOR)/ADApp/Db/NDStdArrays.template", "P=${EPICS_HOSTNAME}-$(BPM_NUMBER):,R=FOFB_B:,PORT=FOFB_B_Array,ADDR=0,TIMEOUT=1,TYPE=Int32,FTVL=LONG,NELEMENTS=$(WAVEFORM_MAX_POINTS)")

NDStdArraysConfigure("FOFB_C_Array", $(QSIZE), 0, "$(PORT)", 27)
dbLoadRecords("$(AREA_DETECTOR)/ADApp/Db/NDPluginBase.template","P=${EPICS_HOSTNAME}-$(BPM_NUMBER):,R=FOFB_C:,PORT=FOFB_C_Array,ADDR=0,TIMEOUT=1,NDARRAY_PORT=$(PORT),NDARRAY_ADDR=27")
dbLoadRecords("$(AREA_DETECTOR)/ADApp/Db/NDStdArrays.template", "P=${EPICS_HOSTNAME}-$(BPM_NUMBER):,R=FOFB_C:,PORT=FOFB_C_Array,ADDR=0,TIMEOUT=1,TYPE=Int32,FTVL=LONG,NELEMENTS=$(WAVEFORM_MAX_POINTS)")

NDStdArraysConfigure("FOFB_D_Array", $(QSIZE), 0, "$(PORT)", 28)
dbLoadRecords("$(AREA_DETECTOR)/ADApp/Db/NDPluginBase.template","P=${EPICS_HOSTNAME}-$(BPM_NUMBER):,R=FOFB_D:,PORT=FOFB_D_Array,ADDR=0,TIMEOUT=1,NDARRAY_PORT=$(PORT),NDARRAY_ADDR=28")
dbLoadRecords("$(AREA_DETECTOR)/ADApp/Db/NDStdArrays.template", "P=${EPICS_HOSTNAME}-$(BPM_NUMBER):,R=FOFB_D:,PORT=FOFB_D_Array,ADDR=0,TIMEOUT=1,TYPE=Int32,FTVL=LONG,NELEMENTS=$(WAVEFORM_MAX_POINTS)")

##################### FOFB POS Waveforms ##########################

NDStdArraysConfigure("FOFB_X_Array", $(QSIZE), 0, "$(PORT)", 30)
dbLoadRecords("$(AREA_DETECTOR)/ADApp/Db/NDPluginBase.template","P=${EPICS_HOSTNAME}-$(BPM_NUMBER):,R=FOFB_X:,PORT=FOFB_X_Array,ADDR=0,TIMEOUT=1,NDARRAY_PORT=$(PORT),NDARRAY_ADDR=30")
dbLoadRecords("$(AREA_DETECTOR)/ADApp/Db/NDStdArrays.template", "P=${EPICS_HOSTNAME}-$(BPM_NUMBER):,R=FOFB_X:,PORT=FOFB_X_Array,ADDR=0,TIMEOUT=1,TYPE=Int32,FTVL=LONG,NELEMENTS=$(WAVEFORM_MAX_POINTS)")

NDStdArraysConfigure("FOFB_Y_Array", $(QSIZE), 0, "$(PORT)", 31)
dbLoadRecords("$(AREA_DETECTOR)/ADApp/Db/NDPluginBase.template","P=${EPICS_HOSTNAME}-$(BPM_NUMBER):,R=FOFB_Y:,PORT=FOFB_Y_Array,ADDR=0,TIMEOUT=1,NDARRAY_PORT=$(PORT),NDARRAY_ADDR=31")
dbLoadRecords("$(AREA_DETECTOR)/ADApp/Db/NDStdArrays.template", "P=${EPICS_HOSTNAME}-$(BPM_NUMBER):,R=FOFB_Y:,PORT=FOFB_Y_Array,ADDR=0,TIMEOUT=1,TYPE=Int32,FTVL=LONG,NELEMENTS=$(WAVEFORM_MAX_POINTS)")

NDStdArraysConfigure("FOFB_Q_Array", $(QSIZE), 0, "$(PORT)", 32)
dbLoadRecords("$(AREA_DETECTOR)/ADApp/Db/NDPluginBase.template","P=${EPICS_HOSTNAME}-$(BPM_NUMBER):,R=FOFB_Q:,PORT=FOFB_Q_Array,ADDR=0,TIMEOUT=1,NDARRAY_PORT=$(PORT),NDARRAY_ADDR=32")
dbLoadRecords("$(AREA_DETECTOR)/ADApp/Db/NDStdArrays.template", "P=${EPICS_HOSTNAME}-$(BPM_NUMBER):,R=FOFB_Q:,PORT=FOFB_Q_Array,ADDR=0,TIMEOUT=1,TYPE=Int32,FTVL=LONG,NELEMENTS=$(WAVEFORM_MAX_POINTS)")

NDStdArraysConfigure("FOFB_SUM_Array", $(QSIZE), 0, "$(PORT)", 33)
dbLoadRecords("$(AREA_DETECTOR)/ADApp/Db/NDPluginBase.template","P=${EPICS_HOSTNAME}-$(BPM_NUMBER):,R=FOFB_SUM:,PORT=FOFB_SUM_Array,ADDR=0,TIMEOUT=1,NDARRAY_PORT=$(PORT),NDARRAY_ADDR=33")
dbLoadRecords("$(AREA_DETECTOR)/ADApp/Db/NDStdArrays.template", "P=${EPICS_HOSTNAME}-$(BPM_NUMBER):,R=FOFB_SUM:,PORT=FOFB_SUM_Array,ADDR=0,TIMEOUT=1,TYPE=Int32,FTVL=LONG,NELEMENTS=$(WAVEFORM_MAX_POINTS)")
