TOP = ..
include $(TOP)/configure/CONFIG

install:
	$(TOP)/install/install.sh /opt/epics/startup/ioc/bpm-epics-ioc $(TOP)

uninstall:
	$(TOP)/install/uninstall.sh /opt/epics/startup/ioc/bpm-epics-ioc $(TOP)

clean:

mrproper: clean

